nome: Empregos para atualizar dados
    em funcionamento: ubuntu-mais recente
    passos:
      # Cartões de resumo
      - usos: ações/checkout@v2
      - usa: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ segredos. GITHUB_TOKEN }}
        com:
          NOME DE USUÁRIO: ${{ github.repository_owner }}

      # Animação cobra
      - usos: Platane/snk@master
        id: snake-gif
        com:
          github_user_name: JuBlancoo
          svg_out_path: dist/github-contribution-grid-snake.svg
      - usos: crazy-max/ghaction-github-pages@v2.1.3
        com:
          target_branch: saída
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ segredos. GITHUB_TOKEN }}
